### ISSUE TITLE
UC 02.02.01 browse open requests based on location

### ISSUE THREAD

**Issue by ChinaHuxin** [CMPUT301W20T01/boost#25]
Implement just from the driver's current location first.
Use projection of a (lat, long) pair to UTM coordinates. Get rides within certain meters around the driver's location.
Add a "moveable" point later.

**Comment by nhtnhan** [comment]
**Partial User Story:**
US 04.01.01
As a driver, I want to browse and search for open requests by geo-location.

**Rationale:**
To make sure updating open request DB 
To filter request based on location 
To prevent drivers from taking recently accepted request

**Notes:**
Might update and modify open request DB
