### ISSUE TITLE
UC 02.06.01 notified if ride offer accepted

### ISSUE THREAD

**Issue by ChinaHuxin** [CMPUT301W20T01/boost#30]
**Partial User Story:**
_US 05.03.01_
As a driver, I want to be notified if my ride offer was accepted.

**Rationale:**
- To make sure ride offer is accepted once
- To make sure ride request is accepted at the same time
- To prevent other drivers to see the accepted request
---
Notes:
Might implement MVC
Might update current status for both ride offers and ride request
Might update DB of available active request

**Comment by nhtnhan** [comment]
Partial User Story:
US 05.03.01
As a driver, I want to be notified if my ride offer was accepted.

Rationale:
To make sure ride offer is accepted once 
To make sure ride request is accepted at the same time
To prevent other drivers to see the accepted request

Notes:
Might implement MVC
Might update current status for both ride offers and ride request
Might update DB of available active request
