### ISSUE TITLE
UC 01.07.03 generate QR bucks QR code

### ISSUE THREAD

**Issue by ChinaHuxin** [CMPUT301W20T01/boost#35]
**Partial User Story:**
_US 08.01.01_
As a rider, I wish to generate a QR-Bucks QR Code for my driver to scan to pay them.

**Rationale:**
- To pay the driver a previously decided upon price
---
**Notes:**
Generate and store when both rider and driver agree to a payment amount
Should be able to access when the ride ends

**Comment by andremures** [comment]
closed in #107
